sudo: required
os: linux
language: cpp
matrix:
   include:
      - os: linux
        dist: trusty

install:
 - sudo apt-get update -qq
 - sudo apt-get install libgsl0-dev libblas-dev
 - sudo apt-get install libboost-all-dev
 - sudo apt-get install netcdf-bin libnetcdf-dev
 - sudo apt-get install libgtest-dev
 - sudo pip install cpp-coveralls

script:
 - make test
 - make

after_success:
 - coveralls --gcov-options '\-lp'

#deploy:
#  provider: launchpad
#  slug: "~christian-skarby/gridpp/master"
#  oauth_token:
#    secure: "QNH5xUjkO3sP26Ncd5e8m6yV9LVP9Qhdku9uar+EDEZccy2amwNfi0RZ3mhalw8wvJUTbKwJGAzxoWCGUspg2ptRUngKNgmuLSYpCxNKJpm5bQrBBgyhAWsQFOpOqk+nEFKUiWnAe5mgP2MU89+ZWEk5TK5vBt1wclK8CaZ+dwo="
#  oauth_token_secret:
#    secure: "b/4eRApZpX3ytYcIf2Z+F5j398/zQnU8sszsZeKkZU/q5j5TF1B5dmRVODIB2JvGhXqukHUdhu7p1oja/GcAZ4a+VF3IuxIe/HaSCMHUoryeNeIzjPhpCBDY21U7kFkPjbMVJGuVcMvOXcpRJ7b5baiW/iGyFx/z3WGSN8Z7R+k="
#  on:
#    tags: true
